language: cpp
sudo: required
dist: xenial
compiler:
  - gcc
os:
  - linux
before_install: sudo apt-get install -y extra-cmake-modules libvulkan-dev vulkan-utils build-essential libx11-xcb-dev mesa-vulkan-drivers && ./update_external_sources.sh
addons:
  apt:
    update: true

script: ./configure.sh -e -u /usr/include/vulkan/ -v /usr/lib/x86_64-linux-gnu/libvulkan.so && cd build && make && cd GLES/unitTests && ./arrays_tests

